# basic options

title: Will
author: 
  name: Aiden Forsyth
description: Aiden Forsyth's personal blog

# Build setting
markdown: kramdown
theme: minima

# Social links
instagram_username: aiden.forsyth
linkedin: aidenforsyth
