# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog

# Build setting
markdown: kramdown
theme: minima
skin: dark

# Social links
instagram_username: aiden.forsyth
