# basic options

title: Will
author: By Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true
language: en
avatar: /assets/Headshot.jpg
url: https://www.aiden-forsyth.github.io/Will

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# Build setting
markdown: kramdown
theme: minima
highlighter: rouge
gems: [jekyll-paginate]
plugins:
  - jekyll-seo-tag
  - jekyll-feed
# Social links
instagram_username: aiden.forsyth
linkedin_username: aidenforsyth
