# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true

# Build setting
markdown: kramdown
theme: minima

# Social links
instagram_username: aiden.forsyth
