# basic options

title: Will
author: By Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true
language: en
avatar: /assets/Headshot.jpg
url: https://www.aiden-forsyth.github.io/Will

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# Build setting
markdown: kramdown
theme: minima
highlighter: rouge
gems: [jekyll-paginate]
plugins:
  - jekyll-seo-tag
  - jekyll-feed
# Social links
instagram_username: aiden.forsyth
linkedin_username: aidenforsyth

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
