# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# Build setting
markdown: kramdown
theme: minima
highlighter: rouge

# Social links
instagram_username: aiden.forsyth
linkedin: aidenforsyth
