# basic options

title: Book fun club
author: 
  name: By Aiden
description: Personal reflections
timezone: America/Montreal
search: true
language: en
url: https://www.aiden-forsyth.github.io/BookFunClub
rss: true

# Build setting
markdown: kramdown

theme: minima
highlighter: rouge
gems: [jekyll-paginate]
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  skin: dark

