# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true
flavicon: assets/speech_bubble.png

# Header / Footer Text
header_text: Welcome!
header_feature_image: assets/Headshot.jpg
# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"


# Build setting
markdown: kramdown
theme: minima
highlighter: rouge

# Social links
instagram_username: aiden.forsyth
rss: true
linkedin: www.linkedin.com/in/aidenforsyth/
