# basic options

title: Willful reflections
author: 
  name: By Aiden Ari Forsyth
description: Personal reflections
timezone: America/Montreal
search: true
language: en
url: https://www.aiden-forsyth.github.io/Will
rss: false

# Build setting
markdown: kramdown

#theme: minima
highlighter: rouge
gems: [jekyll-paginate]
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
#remote_theme: 
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  social_links:
    instagram: aiden.forsyth
    linkedin: aidenforsyth
  skin: dark
