# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog

# Build setting
markdown: kramdown
theme: minima
highlighter: rouge

# Social links
instagram_username: aiden.forsyth

