# basic options

title: Will
author: Aiden Forsyth
description: Aiden Forsyth's personal blog
timezone: America/Montreal
search: true
RSS: false
language: en

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# Build setting
markdown: kramdown
theme: minima
highlighter: rouge
gems: [jekyll-paginate]

# Social links
instagram_username: aiden.forsyth
linkedin: aidenforsyth
